apiVersion: v1
kind: Namespace
metadata:
  name: chip
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chip-s3-shared
  namespace: chip
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  csi:
    driver: s3.csi.aws.com
    volumeHandle: "chip-s3-shared"
    volumeAttributes:
      bucketName: "linuxtips-kubernetes-cluster-767397849711-chip-shared"
      region: "us-east-1"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chip-s3-shared
  namespace: chip
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: chip-s3-shared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chip
  name: chip
  namespace: chip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chip
  template:
    metadata:
      labels:
        app: chip
        name: chip
        version: v1
    spec:
      containers:
      - name: chip
        image: fidelissauro/chip:v1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Custom-Header
              value: Awesome
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "false"
        - name: CHAOS_MONKEY_MODE
          value: "critical"
        - name: CHAOS_MONKEY_LATENCY
          value: "true"
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"
        - name: CHAOS_MONKEY_MEMORY
          value: "true"

        volumeMounts:
        - name: chip-volume
          mountPath: /data
      volumes:
      - name: chip-volume
        persistentVolumeClaim:
          claimName: chip-s3-shared

      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: chip
  namespace: chip
  labels:
    app.kubernetes.io/name: chip
    app.kubernetes.io/instance: chip
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP
