apiVersion: v1
kind: Namespace
metadata:
  name: chip
---
# Criar uma StorageClass que monta o EFS criado
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: chip-efs-shared
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0182ca2a0f06dc9b9
  directoryPerms: "777"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# Criar um PVC usando o SC criado
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chip-efs-shared
  namespace: chip
spec:
  storageClassName: chip-efs-shared
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chip
  name: chip
  namespace: chip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chip
  template:
    metadata:
      labels:
        app: chip
        name: chip
        version: v1
    spec:
      containers:
      - name: chip
        image: fidelissauro/chip:v1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Custom-Header
              value: Awesome
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "false"
        - name: CHAOS_MONKEY_MODE
          value: "critical"
        - name: CHAOS_MONKEY_LATENCY
          value: "true"
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"
        - name: CHAOS_MONKEY_MEMORY
          value: "true"

        volumeMounts:
        - name: chip-volume
          mountPath: /data
      volumes:
      - name: chip-volume
        persistentVolumeClaim:
          # Montar o EFS Shared do EFS
          claimName: chip-efs-shared

      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: chip
  namespace: chip
  labels:
    app.kubernetes.io/name: chip
    app.kubernetes.io/instance: chip
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP
