apiVersion: v1
kind: Namespace
metadata:
  name: chip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chip
  name: chip
  namespace: chip
spec:
  replicas: 50
  selector:
    matchLabels:
      app: chip
  template:
    metadata:
      labels:
        app: chip
        name: chip
        version: v1
    spec:

      # nodeSelector:
      #   karpenter.sh/nodepool: chip-capacity

      topologySpreadConstraints:
      # Distribuir capacity's com base em parametros de zona e tipo de instancia
      - maxSkew: 1
        # O "node.kubernetes.io/instance-type" é usado pra manter instancias balanciadas por tipos de instancia diferentes
        # topologyKey: "node.kubernetes.io/instance-type"
        # O "topology.kubernetes.io/zone" é usado pra manter instancias balanciadas por avaiability zones diferentes
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: chip
      # - maxSkew: 1
      #   topologyKey: "kubernetes.sh/capacity-type"
      #   whenUnsatisfiable: ScheduleAnyway
      #   labelSelector:
      #     matchLabels:
      #       app: chip

      containers:
      - name: chip
        image: fidelissauro/chip:v1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Custom-Header
              value: Awesome
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "false"
        - name: CHAOS_MONKEY_MODE
          value: "critical"
        - name: CHAOS_MONKEY_LATENCY
          value: "true"
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"
        - name: CHAOS_MONKEY_MEMORY
          value: "true"
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: chip
  namespace: chip
  labels:
    app.kubernetes.io/name: chip
    app.kubernetes.io/instance: chip
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP
